kind: pipeline
name: default

steps:
- name: test-and-deploy
  image: node
  commands:
  - cd app
  - npm install
  - npm test
  - cd ..
  - cp -R app/* /mnt/
  volumes:
    - name: web
      path: /mnt

volumes:
- name: web
  host:
    path: /var/www/meta-open-database
